### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by ChaseBacon** [GreeNyTMs/grn_wallet#1]
So the wallet works but im getting a error in F8

SCRIPT ERROR: @grn_wallet/client/client.lua:14: attempt to call a nil value (global ' PutOnBag')

any idea?

**Comment by ChaseBacon** [comment]
So, i commented out lines 14 to 18 and the error stopped FYI

**Comment by GreeNyTMs** [comment]
Ohh, thanks, i will update that
